pub mod buffer;
pub mod clip;
pub mod device;
pub mod engine;
pub mod error;
pub mod file_io;
pub mod hardware;
pub mod instrument;
pub mod instrument_processor;
pub mod midi_event;
pub mod midi_input;
pub mod player_processor;
pub mod processor;
pub mod sine_synth;
pub mod stream;
pub mod synth;
pub mod timeline;
pub mod timeline_processor;
pub mod transport;

pub use buffer::{AudioBuffer, OwnedAudioBuffer};
pub use clip::{AudioClip, AudioPlayer, PlaybackState};
pub use device::{AudioDeviceInfo, DeviceManager};
pub use engine::{AudioEngine, EngineConfig};
pub use error::{AudioError, AudioResult};
pub use file_io::{load_audio_file, save_wav_file, AudioFileInfo, AudioFormat};
pub use hardware::{find_focusrite_devices, scan_hardware_devices, HardwareDevice};
pub use instrument::VirtualInstrument;
pub use instrument_processor::{InstrumentProcessor, PreviewHandle};
pub use midi_event::{freq_to_pitch, pitch_to_freq, MidiEvent, MidiEventType, MidiNote};
pub use midi_input::MidiInput;
pub use player_processor::{ClipPlayerProcessor, PlayerHandle};
pub use processor::{AudioProcessor, ProcessorConfig};
pub use stream::{get_low_latency_config, AudioStream};
pub use synth::{Envelope, SimpleSynth, SineSynth, Voice};
pub use timeline::{MidiClip, MidiTrack, Sequencer, Timeline};
pub use timeline_processor::{TimelineHandle, TimelineProcessor, TransportCommand};
pub use transport::{TimeSignature, Transport, TransportBuilder, TransportMonitor, TransportState};

pub const MAX_CHANNELS: usize = 32;
pub const DEFAULT_SAMPLE_RATE: u32 = 48000;
pub const DEFAULT_BUFFER_SIZE: u32 = 256;
pub const TARGET_LATENCY_MS: f32 = 5.0;
